version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "EyMt68bBzwU5kt3N4FpIMyvNfA3BGWcNP37ITmzelNBUIUkwtsgK9NWOqJZUGVWFISf8+8fKBlTwB45SBNnMHfGZKGCevArxSxjz5LLRQS8TTebuN+hFVTdzjsvD7xn50Bag1m8wkuQYe/GfxEK+EgzZQIINcTJ6I97L13lqxOE="
    - secure: "fL72MC2ykcNhv3UUc5W6L9n+ZiclPO5dkLTKMrE7NxbESV6Cdyu98/foXNm9myGbx08RjsXAHloGU7vnZ3zedEZ68SU953xfsW4/XSc8mReZcbdd0qBW7O1FeglMr4rww7naYIJbpxmgVZjOiMu+WKE0KjL1LdWa/7Eo0cuwR7Y="
