version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "ep5rzytUAkdawCl0HOOaXf1tJCHoevltYo3o7gM/Q7CfKXzWi9A3i31V742+eh51OZlm7BhuitczuaRXgmvcge3Ye7WPVWPObxkpZ90NSgXeOsqDwBKsiYpOZEqQVYuNb4AXwMJC2VhZUF3V7ZDvteLRSbsBSkjd1LQOKK9ctjA="
        - secure: "OLECWnDRgm1wlYXagPRX3KJ/iAUI94BFokgfmYbKCYRrr7CeFxXEGkzVFgrCtNgxzgLfR0xmqegnHvAo/4lDRqmzf9gZILKeruMndrI8uJ9bM4mVoJ182pq54wghc0WHtheDfqYPbXYgV8D4AmMepOvD30dzkt1dCFhR9LxtJ34="
