version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings .travis-settings.xml";  fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: GQM/PGuY6WvMYRSlY/hvq/0fYZyT2kIa1c8IMzP7TXgLFwb/kje+xVSN0w76HOuPkbB/XfJUdEBXxchQGlCbJT55sQhBRjvux691M3T9FT4ozZJctdYfUVK3wnlD4yqThghTVLjLwdAXU9/1BofXRHJ/jmGlWQfQoVCDLiazXO8=
  - secure: R2LYdT8iRuf6mTUjUbX+nevCVRMz2HvDjrOh58tQ6IDLtzcjy+LeK9STqUVTooKPAq2vttI30Bvt/LqKJn6X+BbHhZ0/nokldMgNORQDJCrGejQItvErMvQAz1Lq4h40sOLHb4FJi/zBNHX47aF6g58Z2rJxRhdIPWdko/yWRGg=
