version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "AxmOKcJ1e38+84HESo3dQTzDfmGZSXbP9Vx02svXEAUg8saQdrOiol3v3oTKarRvFWx9ThU+GC1f+nyp3yjAjCQ9y8l/jrxD16NJy2rpwhnKwo85hySJZagj8Li4k7od+EwkqL0TW9n53+kAntoQdCL1R8uegZ0cHbIzF9S26kc="
    - secure: "WNuMiDKU2c3dVG3f3AuJmA0r+xJmFUeHvd4taG2Ff/Ki33VVyRFvvymMgM5cXbmlHgJfrSERyHnAj3M4tMgEcLxUCpKs3icpGeb0eK7MdC7VsVY9YY2Q5gaVnPe1pvBfSmOYM/h4C8KYmnmTpR4Tu0ZLlmLBVYedH5yDp3K1gVM="